name: record_extender
description: "Generates record extensions for multiple record sizes."
version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.2.0

  record_extender_annotations:
    path: ../record_extender_annotations

dev_dependencies:
  test:
  build_runner:
  build_verify:
  build_test:
  source_gen_test: ^1.0.6
  lints: ^3.0.0

