name: record_extender_annotations
description: "Annotations for record_extender source generator"
repository: https://github.com/alex-gutev/record_extender/tree/master/record_extender_annotations
version: 0.1.0

environment:
  sdk: '>=2.18.6 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
